### ISSUE TITLE
clean_did_info

### ISSUE THREAD

**Issue by brettdavidheiser** [isoverse/clumpedr#13]
With in the function clean_did_info() the `Line` info is not in our did_files pulled out of isoreader. I bet his has to do with how we have isodat configured. We will need to have error checking or the ability to pass in what types of user info exist for each mass spec.

**Comment by japhir** [comment]
Ah ok, so they should all become input options, or maybe one vector of column names that we then iteratively parse? Maybe this part---of parsing the columns as the correct types---should actually be part of isoreader though? @sebkopf Then this function would only add a column masspec with the name of the mass spectrometer (in case you're working on multiple) and get out the first rows of sample and standard gas so that we can add the s44_init and r44_init columns.

**Comment by sebkopf** [comment]
I agree, that's a great idea to have a broad column data type parsing function in isoreader that casts data columns into different data formats and deals well with missing columns. I'm thinking something flexible but easy to use maybe this (pseudocode):

```
# @param integer tidyverse select syntax for columns that should be parsed as integer (using parse_integer)
# @param other columns to apply the other_func to
# @param other func parsing function to apply to the other columns
iso_parse_file_info <- function(isofiles, integer = c(), double = c(), character = c(), other = c(), other_func = NULL) {
  # figure out which columns each of the colum selectors refers to
  # then parse the found columns with parse_integer, parse_double, parse_character, other_func (if provided), respectively
  # throw warnings if some columns do not exist in ANY files
  # return isofiles (or data frame? or allow for both?)
}
```

Let me know what you think.

I also think the iso_recode column function will be helpful to make the column name issue between different mass specs easier to work with (https://github.com/isoverse/isoreader/issues/11, sorry that's at the top of my list but the tests are not quite ready yet).

Generally, I think this raises a bigger question about how flexible this package should be. At the moment there is a fair bit of column names that are thermo specific and will not work with different configurations or with nu data files. e.g. `parse_info` and `filter_clumped` have a little bit of this but I think the above functions could work well to help with parse info. I think `filter_clumped` is a tricky concept because it is so specific to both Thermo format and the specific method names - could we just leave this without a function as a direct call in your vignette as an example? (plus add the help notes about regexps in the vignette instead?) I appreciate the idea of making it as simple as possible for users but a function for something that can be done with a fairly clear single line call might add more clutter than it solves. It seems in this case the vignette could just have this, no?

`filt <- dids %>% iso_filter_files(str_detect(Method, "Clumped.*met"))`

**Comment by japhir** [comment]
That sounds great! I was thinking of something earlier in the pipeline, where when isoreader first reads in `Weight [mg]` it tries to `parse_double()` already, with the appropriate warning messages included in the warnings column of the file? But having it read in the data as "raw as it gets" and then subsequently telling it how to parse certain columns would also make sense.

> Generally, I think this raises a bigger question about how flexible this package should be. 

Yes, this was a problem that I ran into quite often while programming. I tried to take into account most of the time, by having the column names to which functions refer as parameters, but I also want to make the functions easy to use for novices.

> I think filter_clumped is a tricky concept because it is so specific to both ...

That's a very fair point. Got rid of the function and updated the vignette. Thanks!

**Comment by sebkopf** [comment]
@japhir okay, select, rename and mutate are all implemented in the dev version as extensions of the `dplyr` generics as well as the more desriptive `iso_select_file_info`, `iso_rename_file_info`, `iso_mutate_file_info` (and examples are in the vignettes). Of course the mutate one is the most useful, now just need to add the `iso_parse_file_info` as a shortcut for type casting file info and we're in good shape with all these in base isoreader :) sorry, taking a while to do this right. The rename function could be useful for getting all file info to have the names you're expecting for it in clumpedr, maybe?

**Comment by sebkopf** [comment]
okay, `iso_parse_file_info` is implemented (https://github.com/isoverse/isoreader/issues/61), thanks for the input on these!

**Comment by japhir** [comment]
Awesome, great work! Very educational to take a look at how you're creating S3 methods for your class of objects :).
