### ISSUE TITLE
remove all plotting functions?

### ISSUE THREAD

**Issue by japhir** [isoverse/clumpedr#17]
I was considering that it may be smart to get rid of all the functions that I don't use a lot before this (hopefully) starts getting used by other people, so there will be less code to maintain and the package will be more focussed on functionality in stead of feature overload. What do you think, @sebkopf?

**Comment by sebkopf** [comment]
good thinking, definitely always recommend that, that's the main reason we moved all plotting from isoreader into isoprocessor to make a more streamlined package with one primary purpose rather than feature overload

**Comment by japhir** [comment]
I've been stripping stuff out and doing some refactoring. What are your thoughts on wrapper functions? e.g. [delta_values()](https://github.com/isoverse/clumpedr/blob/master/R/delta_values.R), which is a wrapper for abundance_ratios, abundance_ratios, little_deltas, bulk_and_clumping_deltas.

**Comment by sebkopf** [comment]
Hi @japhir . I don't like wrapper functions because they obscure functionality to the user and make it harder to understand what's going when someone reads a knitted RMarkdown report. Ideally in reports the commands all make it very clear what's going on with each function verbified if appropriate, e.g. `calculate_xyz() %>% calculate_abc %>% summarize_klm()` makes for a very clear pipe of what's happening. Also, users don't learn how to use the functions I want them to learn to use from wrappers. I appreciate wrappers help new users getting started and used to use them a lot but have since shifted towards providing good examples in vignettes that beginners can adjust as needed instead of using wrappers. Also GUI's that generate code examples can help with this (partially the purpose of `isoviewer`) but that's a pretty big rabbit hole I don't generally recommend ;)

As for plotting functions, if they are just wrappers I try to avoid them, if they provide some helpful functionality that's very frequently used for the subject data I think they're okay. I'm still on the fence for the plotting functions in isoprocessor which ones to keep and which ones to ultimately retire.

just my two cents, hope that helps!
