### ISSUE TITLE
serve a pkgdown website

### ISSUE THREAD

**Issue by japhir** [isoverse/clumpedr#22]
I've pushed the pkgdown workflow, which for my own repos serves the package at japhir.github.io/PKG
The build is succesful, but somehow isoverse.github.io/clumpedr doesn't work (likely because it redirects to isoverse.org/clumpedr?)

**Comment by japhir** [comment]
@sebkopf could you help out here? :)

**Comment by japhir** [comment]
Until this works, the vignette can be previewed here:

[direct link using htmlpreview URL](https://htmlpreview.github.io/?https://github.com/isoverse/clumpedr/blob/gh-pages/articles/clumped.html)

**Comment by sebkopf** [comment]
Hi @japhir , great work! sorry about the slow response, had knee surgery last week and been pretty out of it since. 

The setup was almost complete, the only thing you missed was telling GitHub were to find the pkgdown-generated site. I updated that in the Settings under GitHub Pages (https://github.com/isoverse/clumpedr/settings/pages) so now the site works and is available at https://www.isoverse.org/clumpedr/

Note that I also setup a CNAME record for clumpedr.isoverse.org but that only works if you tell pkgdown that the site is (also) available at this address. You can do that by setting up a `_pkgdown.yml` config file, take a look at the one from isoreader (which has way more specified that necessary, most of those settings are completely optional, just the URL matters): https://github.com/isoverse/isoreader/blob/master/_pkgdown.yml

**Comment by japhir** [comment]
Oof I hope you get better soon!

Thanks for fixing the website, I've also just pushed an extremely basic `_pkgdown.yml` with only the url field in it. Not really sure what a CNAME record is, but I hope that it does something important ;-). Ah is it the alias to https://clumpedr.isoverse.org?
