### ISSUE TITLE
Document the `quiet` and `genplot` parameters correctly

### ISSUE THREAD

**Issue by japhir** [isoverse/clumpedr#5]
The build checks keep complaining that `quiet` and `genplot` arguments in various functions are currently undocumented. I don't know how to exclude them from the checks. Should I write their documentation somewhere, and have all the functions that use them `@inheritParams` from that definition? @sebkopf a little help? :)

**Comment by sebkopf** [comment]
yes, exactly. You document it in one function and then `@inheritParams` everywhere else. no way around CRAN rules unless you want to write an elaborate explanation to the cran team (which they may or may not accept ;)


on a related note - if you want you could share some default parameters with isoreader namespace so that e.g. info messages on/off works across packages. isoprocessor does this with the following approach:

```
# reexport info message on/off
#' @export
isoreader::iso_turn_info_messages_on

#' @export
isoreader::iso_turn_info_messages_off
```

and then for the default function something like this (isoprocessor does a more elaborate thing here because of quoted defaults but I think those were a bad idea to begin with ;)

```
# retrieve package settings, internal function, not exported
default <- function(name, allow_null = FALSE) {
  name <- enquo(name) %>% quos_to_text(variable = "setting")
  value <- isoreader:::default(!!sym(name), allow_null = TRUE)
  if (is.null(value)) # not in isoreader settings
      value <- getOption(str_c("clumpedr.", name))
  if (!allow_null && is.null(value))
    stop("clumpedr setting '", name, "' does not exist", call. = FALSE)
  return(value)
}
```

**Comment by japhir** [comment]
That looks nice! I'll see if I can inherit `quiet`.

Also, how is your `quos_to_text()` different from `rlang::quo_name()`? I just copied it over to [R/nse.R](https://github.com/isoverse/clumpedr/blob/dev/R/nse.R) because [R/settings.R](https://github.com/isoverse/clumpedr/blob/dev/R/settings.R), which I mostly copied and adjusted, uses it.

**Comment by japhir** [comment]
I tried implementing this now in settings.R, but the compiler still whines about the lack of documentation for quiet (and of course genplot). Could you have a look at my latest release and see where it goes wrong?

**Comment by japhir** [comment]
Should be fixed now. Documented in `utils.R` and inheriting everywhere else. Same for new `...` argument to most functions, which forces named argument matching.
